language: node_js

node_js: 
  - 16

os: linux
dist: focal

branches:
  only:
    - main

cache: 
  directories:
    - node_modules

install:
  - npm install
  - npm install -g yarn

script:
  # - yarn lint
  - yarn build
  - mv build/index.html build/404.html

deploy:
  provider: pages
  cleanup: false
  token: $github_token
  strategy: git
  local_dir: build
  on:
    branch: main
